### ISSUE TITLE
Why is the Europe/London time zone set in some of the helper Dockerfiles?

### ISSUE THREAD

**Issue by tlindsay42** [awslabs/automated-security-helper#15]
The `Europe/London` time zone is not the same thing as `UTC`. Is there a reason for configuring the time zone in the following examples?

### Examples

https://github.com/aws-samples/automated-security-helper/blob/7e2ecd8c033115daabdf9f1c246e976cae8ebc99/helper_dockerfiles/Dockerfile-cdk#L5-L6

https://github.com/aws-samples/automated-security-helper/blob/7e2ecd8c033115daabdf9f1c246e976cae8ebc99/helper_dockerfiles/Dockerfile-yaml#L5-L6

**Comment by awsntheule** [comment]
The project is moving from a multi-container architecture to a single container, which will be set to UTC. Since those Dockerfiles will be deprecated we will not be changing this.
