### ISSUE TITLE
Issue with Dockerfile-cdk, and returning with '1' with latest version -> Dockerfile-cdk :   1

### ISSUE THREAD

**Issue by upi360** [awslabs/automated-security-helper#33]
I was trying to scan my code in cloud9 cdk environment and getting the below error message at end of the scan. I am using the latest version of the ASH  - 1.1.0-e-01Dec2023

=> ERROR [5/6] RUN cd /utils/cdk-nag-scan &&     npm install              0.3s
------
 > [5/6] RUN cd /utils/cdk-nag-scan &&     npm install:
#0 0.275 /bin/sh: 1: cd: can't cd to /utils/cdk-nag-scan
------
Dockerfile-cdk:18
--------------------
  17 |     
  18 | >>> RUN cd /utils/cdk-nag-scan && \
  19 | >>>     npm install
  20 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c cd /utils/cdk-nag-scan &&     npm install" did not complete successfully: exit code: 2
Unable to find image 'scan-11607:latest' locally
docker: Error response from daemon: pull access denied for scan-11607, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.
Dockerfile Dockerfile-cdk returned 125
Error response from daemon: No such container: scan-11607

**Comment by scrthq** [comment]
@upi360 Working on this now, thank you for raising!

**Comment by scrthq** [comment]
hi @upi360 - This should be resolved now in `main` by PR #34 . Please let us know if you are still having issues by reopening this ticket if anything persists. Thank you, have a nice day!
