### ISSUE TITLE
Feature request: Update documentation with single-container architecture details and CI examples

### ISSUE THREAD

**Issue by scrthq** [awslabs/automated-security-helper#38]
## Use case

Documentation needs to be updated with details around configuring and using the new, single-container architecture of ASH, as well as provide examples of using ASH to scan code in a CI pipeline.

## Solution/User Experience

Documentation exists, ideally in the form of a searchable documentation site such as MkDocs, and includes updated details around configuring and using ASH as well as examples of using ASH in CI pipelines.

## Alternative solutions

_N/A_

**Comment by climbertjh2** [comment]
The `CONTRIBUTING.md` page should also be updated to note that commit messages should/must conform to the Conventional Commit documentation going forward.
