### ISSUE TITLE
Scanner option to cancel the run, when there are many files in `--source-dir` not working

### ISSUE THREAD

**Issue by climbertjh2** [awslabs/automated-security-helper#53]
With the latest updates, it looks like the option to cancel the run of the scan when there are "many" files in the source directory is no longer working.

It may be due to the scan script being run in a container now, so the sleep/delay is not interruptable/stoppable with a CTRL-C entry.

Symptom: see the following in the output, attempt CTRL-C to stop ... but the scan does not stop:

```
ASH found 9147 file(s) in the source directory...
Depending on your machine this might take a while...
Waiting 5 seconds in case you want to stop (use CTRL-C)...
```

**Comment by awsntheule** [comment]
Hey Tim, PR #71 should fix this. Please confirm that this issue is resolved.

**Comment by climbertjh2** [comment]
I tested this today - it is working again!

Thank you.  Closing this one.
