### ISSUE TITLE
Support pnpm audit

### ISSUE THREAD

**Issue by bestickley** [awslabs/automated-security-helper#56]
I have a PNPM Monorepo. When I run ash on it, it uses `npm audit` which requires a package-lock.json which my project does not have. I have a pnpm-lock.yaml. Please support PNPM projects and use `pnpm audit`. Thank you!

**Comment by awsntheule** [comment]
Hey @bestickley, ASH should now use pnpm when appropriate with PR #66. Please clone the latest changes and try again when you get a chance.

**Comment by bestickley** [comment]
Thank you, @awsntheule, I'll try to get to this next week.

**Comment by awsntheule** [comment]
@bestickley, have you had a chance to confirm your issue is fixed?

**Comment by bestickley** [comment]
Confirmed this worked by seeing aggregated_results.txt:

>>>>>> Begin pnpm audit output for /src >>>>>>

No known vulnerabilities found

<<<<<< End pnpm audit output for /src <<<<<<

Thank you, @awsntheule !
