### ISSUE TITLE
v1.3.0 - grype and syft scanners are not running against items in git repositories

### ISSUE THREAD

**Issue by climbertjh2** [awslabs/automated-security-helper#72]
I have found that with v1.3.0, the `grype` and `syft` scanners are not scanning files that they should - but only when the `--source-dir` is set at a git repository.  If the `--source-dir` is not a git repository root, then the scanners find the files.

I have narrowed this down to the use of a `--tmpfs` mount for the container run.

**Comment by climbertjh2** [comment]
I am working on a PR for this.

**Comment by scrthq** [comment]
This looks good as of PR #73 ! Ready to close when you are done confirming from my perspective, I'm seeing Syft kicking in again where I wasn't previously

**Comment by climbertjh2** [comment]
Yes - this is fixed now.  Closing.
