### ISSUE TITLE
Feature request:  Include AWS CLI in the ASH image

### ISSUE THREAD

**Issue by climbertjh2** [awslabs/automated-security-helper#76]
This is a feature request put up for discussion.

When running the ASH image in build automation environments, it could be useful to have the AWS CLI included in the installed packages in the image.

While this is not needed for running any of the tools that ASH uses, it seems to be a common scenario that some AWS-related actions might be taken during an ASH scan processing - for example - writing to an S3 bucket/object.

Let the discussion begin.

**Comment by scrthq** [comment]
While I agree this would be handy for CI, I don't think we should bundle things that don't explicitly serve the functionality of the tool. CI base images are meant to be built on for anything extra needed, so I don't necessarily see it as a bad thing if someone has to explicitly add a tool like AWS CLI to their own pipeline job using ASH as the base image. My 2 cents.

**Comment by climbertjh2** [comment]
Fair enough point.

There is always the option that someone can fork the repo and add that in themselves to the `Dockerfile`.

Closing as not planned.
