### ISSUE TITLE
container image for ASH runs as root inside the container

### ISSUE THREAD

**Issue by climbertjh2** [awslabs/automated-security-helper#78]
As a recommended practice, code running in containers should run as non-root (UID 0).  This is an added protection in case the container is run in privileged mode.

Please update the `Dockerfile` to add an `adduser` to the container build and then `USER <uid>` in the build of the container.

**Comment by climbertjh2** [comment]
working on this one.

**Comment by climbertjh2** [comment]
PR #79 is provided to address this item

**Comment by scrthq** [comment]
@climbertjh2 I think we can close this one out now

**Comment by climbertjh2** [comment]
With `v2.0.0` this is resolved.  Closing.
